version: '3.7'
services:
    db:
        build: 
            context: ./movies-data
            dockerfile: PostgresDockerfile
        volumes:
            - movies-database-volume:/var/lib/postgresql/data
        container_name: movies-database
    api:
        build:
            context: ./MoviesApi
        ports:
            - "5000:80"
        # https://docs.docker.com/compose/compose-file/#links
        links: 
            - db:moviedatabase
        container_name: movies-api
    web:
        build:
            context: ./movies-viewer
        ports:
            - "80:80"
        container_name: movies-viewer

volumes:
    movies-database-volume: