export const ADD_MOVIES = 'ADD_MOVIES';
export const MARK_MOVIES_AS_LOADED = 'MARK_MOVIES_AS_LOADED';
export const MARK_MOVIES_AS_INITIALLY_LOADED = 'MARK_MOVIES_AS_INITIALLY_LOADED';
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';